_wandb:
    value:
        cli_version: 0.22.1
        e:
            z69uwaat5tylusbbsf8hfgsidgwon27b:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: Tarea_1_letra.ipynb
                codePathLocal: Tarea_1_letra.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "92167360512"
                email: campiglianatalia@gmail.com
                executable: /Users/nataliacampigliastemphelet/miniconda3/envs/taller-dl/bin/python
                git:
                    commit: 7b19d17142c2649f65d4754ac7752c9076d4dab4
                    remote: https://github.com/nataliacampiglia/tdl_tarea_1.git
                host: 192.168.1.45
                memory:
                    total: "25769803776"
                os: macOS-15.1-arm64-arm-64bit-Mach-O
                program: ./Tarea_1_letra.ipynb
                python: CPython 3.13.7
                root: /Users/nataliacampigliastemphelet/master/tdl_tarea_1
                startedAt: "2025-10-04T21:01:50.847227Z"
                writerId: z69uwaat5tylusbbsf8hfgsidgwon27b
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 3
                - 14
            "4": 3.13.7
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": darwin-arm64
batch_size:
    value: 256
device:
    value: cpu
dropout:
    value: 0.2
early_stop:
    value: true
label_smoothing:
    value: 0
learning_rate:
    value: 0.002286194885900627
optimizer:
    value: sgd
patience:
    value: 5
seed:
    value: 13
weight_decay:
    value: 0
