_wandb:
    value:
        cli_version: 0.22.1
        e:
            vimpgl3b1k2lbnhzngbzzez7h3ndjk45:
                codePath: Tarea_1_letra.ipynb
                codePathLocal: Tarea_1_letra.ipynb
                email: campiglianatalia@gmail.com
                executable: /Users/nataliacampigliastemphelet/miniconda3/envs/taller-dl/bin/python
                git:
                    commit: 7b19d17142c2649f65d4754ac7752c9076d4dab4
                    remote: https://github.com/nataliacampiglia/tdl_tarea_1.git
                host: 192.168.1.45
                os: macOS-15.1-arm64-arm-64bit-Mach-O
                program: ./Tarea_1_letra.ipynb
                python: CPython 3.13.7
                root: /Users/nataliacampigliastemphelet/master/tdl_tarea_1
                startedAt: "2025-10-04T20:03:33.940579Z"
                writerId: vimpgl3b1k2lbnhzngbzzez7h3ndjk45
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 14
            "4": 3.13.7
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": darwin-arm64
batch_size:
    value: 64
dropout:
    value: 0.2
early_stop:
    value: true
label_smoothing:
    value: 0
learning_rate:
    value: 0.0003668659833374641
optimizer:
    value: adam
patience:
    value: 5
seed:
    value: 7
weight_decay:
    value: 0.0005
