wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0
early_stop:
  value: true
label_smoothing:
  value: 0
learning_rate:
  value: 0.0001918453640550944
optimizer:
  value: sgd
patience:
  value: 5
seed:
  value: 13
weight_decay:
  value: 0
