wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3
early_stop:
  value: true
label_smoothing:
  value: 0.05
learning_rate:
  value: 0.000457202026616065
optimizer:
  value: adam
patience:
  value: 5
seed:
  value: 13
weight_decay:
  value: 0
