wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0.2
early_stop:
  value: true
label_smoothing:
  value: 0
learning_rate:
  value: 0.002286194885900627
optimizer:
  value: sgd
patience:
  value: 5
seed:
  value: 13
weight_decay:
  value: 0
