wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2
early_stop:
  value: false
label_smoothing:
  value: 0
learning_rate:
  value: 0.0003561648518741055
optimizer:
  value: sgd
patience:
  value: 5
seed:
  value: 7
weight_decay:
  value: 0.0001
