wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2
early_stop:
  value: true
label_smoothing:
  value: 0
learning_rate:
  value: 0.004254290541419217
optimizer:
  value: adam
patience:
  value: 5
seed:
  value: 7
weight_decay:
  value: 0
