wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0.2
early_stop:
  value: true
label_smoothing:
  value: 0.05
learning_rate:
  value: 0.003104091358179486
optimizer:
  value: adam
patience:
  value: 3
seed:
  value: 7
weight_decay:
  value: 0.0001
