wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2
early_stop:
  value: false
label_smoothing:
  value: 0.05
learning_rate:
  value: 0.0010429019138807009
optimizer:
  value: sgd
patience:
  value: 5
seed:
  value: 13
weight_decay:
  value: 0
