wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0
early_stop:
  value: false
label_smoothing:
  value: 0.05
learning_rate:
  value: 0.0014495380785476187
optimizer:
  value: adam
patience:
  value: 5
seed:
  value: 13
weight_decay:
  value: 0.0001
