wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0
early_stop:
  value: false
label_smoothing:
  value: 0
learning_rate:
  value: 0.004789031761443692
optimizer:
  value: adam
patience:
  value: 3
seed:
  value: 7
weight_decay:
  value: 0
