wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2
early_stop:
  value: true
label_smoothing:
  value: 0
learning_rate:
  value: 0.0003668659833374641
optimizer:
  value: adam
patience:
  value: 5
seed:
  value: 7
weight_decay:
  value: 0.0005
